<?php

namespace Omnipay\Swipehq\Message;

use Omnipay\Common\Message\AbstractResponse;

/**
 * Swipehq Response
 *
 * @example json {"response_code":200,"message":"OK","data":{"transaction_id":"XXXX","status":"declined","transaction_approved":"no"}}
 */
class PaymentPageCompleteAuthorizeResponse extends AbstractResponse{

    /**
     * Get a message generated by the payment gateway
     *
     * @return string Message
     */
    public function getMessage(){
        return isset($this->data['message']) ? (string) $this->data['message'] : null;
    }


    /**
     * Response code
     *
     * @return string A response code from the payment gateway
     */
    public function getCode(){
        return isset($this->data['response_code']) ? (string) $this->data['response_code'] : null;
    }


    /**
     * Get Transaction Reference
     *
     * @return string A reference provided by the gateway to represent this completed transaction.  Note this is not the identifier_id generated using the createTransactionIdentifier API
     */
    public function getTransactionReference(){
        if(empty($this->data['data'])){
            return null;
        } else {
            $data = $this->data['data'];
            if(empty($data['transaction_id'])){
                return null;
            } else {
                return $data['transaction_id'];
            }
        }
    }


    /**
     * getStatus
     *
     * @return string A status message provided by the gateway to represent the success or failure of the transaction
     */
    public function getStatus(){
        if(empty($this->data['data'])){
            return null;
        } else {
            $data = $this->data['data'];
            if(empty($data['status'])){
                return null;
            } else {
                return $data['status'];
            }
        }
    }


    /**
     * getTransactionApproved
     *
     * @return string Another message provided by the gateway to represent to represent the success or failure of the transaction
     */
    public function getTransactionApproved(){
        if(empty($this->data['data'])){
            return null;
        } else {
            $data = $this->data['data'];
            if(empty($data['transaction_approved'])){
                return null;
            } else {
                return $data['transaction_approved'];
            }
        }
    }


    /**
     * Is the response successful?
     *
     * When we need to redirect the browser we return false as the transaction is not yet complete
     * @return boolean
     */
    public function isSuccessful(){
        if(isset($this->data['data'])){

           $data = $this->data['data'];

           if(isset($data['status'])){
                return $data['status'] === "accepted" || $data['status'] === "test-accepted";
           } else {
               return false;
           } 
        } else {
            return false;
        }
        
    }


}
