<?php

namespace Omnipay\Swipehq\Message;

use Omnipay\Common\Message\AbstractResponse;

/**
 * Swipehq Response
 */
class PaymentPageCompleteAuthorizeResponse extends AbstractResponse{

    /**
     * Get a message generated by the payment gateway
     *
     * @return string Message
     */
    public function getMessage(){
        return isset($this->data['message']) ? (string) $this->data['message'] : null;
    }


    /**
     * Response code
     *
     * @return string A response code from the payment gateway
     */
    public function getCode(){
        return isset($this->data['response_code']) ? (string) $this->data['response_code'] : null;
    }


    /**
     * Get TransactionID
     *
     * @return string A reference provided by the gateway to represent this completed transaction.  Note this is not the identifier_id generated using the createTransactionIdentifier API
     */
    public function getTransactionId(){
        $data = $this->data['data'];

        if(isset($data['transaction_id'])){
            return (string) $this->data['transaction_id'];
        }
    }


    /**
     * Is the response successful?
     *
     * When we need to redirect the browser we return false as the transaction is not yet complete
     * @return boolean
     */
    public function isSuccessful(){
        if(isset($this->data['data'])){

           $data = $this->data['data'];

           if(isset($data['status'])){
               return (string) $this->data['status'] === "accepted" || (string) $this->data['status'] === "test-accepted";
           } else {
               return false;
           } 
        } else {
            return false;
        }
        
    }


}
